[package]
name = "gba-cassowary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3.67"
bitfield = "0.14.0"
bitvec = "1.0.1"
byteorder = "1.4.3"
